spCreateURL: "http://52.9.174.25:9763/client-registration/v0.10/register"
tokenRequestURL: "https://52.9.174.25:8243/token"
appCreateURL: "http://52.9.174.25:9763/api/am/store/v0.10/applications"
generateKeyURL: "http://52.9.174.25:9763/api/am/store/v0.10/applications/generate-keys?applicationId="
subscriptionURL: "http://52.9.174.25:9763/api/am/store/v0.10/subscriptions"
createNewUserURL: "https://52.9.174.25:9443/wso2/scim/Users"
callbackUrl: "http://www.google.com"
tokenScope: "Production"
tokenAPI: "http://52.9.174.25:9763/api/am/store/v0.10/applications"
owner: "admin"
grantType: "password refresh_token"
nexmoAPI: "8b6bf242-2216-4f53-9779-394c60247ea2"
SmsAPI: "92b82a9b-5f9d-4c60-9d00-27aebebf438f"